#pragma once
#include "dapr/property_holder.h"
#include "grenade/common/genpybind.h"
#include "grenade/common/multi_index_sequence.h"
#include "grenade/common/projection.h"
#include "grenade/common/projection_connector/static.h"
#include "hate/visibility.h"
#include <cstddef>

namespace grenade {
namespace common GENPYBIND_TAG_GRENADE_COMMON {

/**
 * Sequence connector defining connectivity by sequences.
 */
struct SYMBOL_VISIBLE GENPYBIND(visible) SequenceConnector : public StaticConnector
{
	/**
	 * Construct sequence connector.
	 * @param input_sequence Sequence of input channels
	 * @param output_sequence Sequence of output channels
	 * @param connection_sequence Sequence of connections in input_sequence x output_sequence space
	 * @throws std:invalid_argument On connection_sequence not being included in input_sequence x
	 * output_sequence
	 */
	SequenceConnector(
	    MultiIndexSequence const& input_sequence,
	    MultiIndexSequence const& output_sequence,
	    MultiIndexSequence const& connection_sequence);

	/**
	 * Get input sequence of connector.
	 */
	virtual std::unique_ptr<MultiIndexSequence> get_input_sequence() const override;

	/**
	 * Get output sequence of connector.
	 */
	virtual std::unique_ptr<MultiIndexSequence> get_output_sequence() const override;

	/**
	 * Get number of synapse parameterizations.
	 * This is equivalent to the number of connections for the SequenceConnector.
	 */
	virtual size_t get_num_synapse_parameterizations(
	    MultiIndexSequence const& sequence) const override;

	/**
	 * Get sequence of indices of synapse parameterizations required by connector.
	 * This sequence describes the indices in the 1d space of synapse parameterizations.
	 * There might be cases, where multiple synapses share the same parameterization (e.g. for
	 * convolutions).
	 * @param sequence MultiIndexSequence for which to get synapse parameterizations
	 * @throws std:invalid_argument On sequence not being included in input_sequence x
	 * output_sequence
	 */
	virtual std::unique_ptr<MultiIndexSequence> get_synapse_parameterization_indices(
	    MultiIndexSequence const& sequence) const override;

	/**
	 * Get sequence of synaptic connections generated by connector.
	 * This sequence describes the connectivity of the synapses between input and output
	 * sequences via their locations in the space input x output sequence.
	 * @param sequence MultiIndexSequence for which to get contained connections
	 * @throws std:invalid_argument On sequence not being included in input_sequence x
	 * output_sequence
	 */
	virtual std::unique_ptr<MultiIndexSequence> get_synapse_connections(
	    MultiIndexSequence const& sequence) const override;

	/**
	 * Get section of connector.
	 * The sequence is required to be included in the connector shape (input_sequence x
	 * output_sequence).
	 * @throws std:invalid_argument On sequence not being included in input_sequence x
	 * output_sequence
	 */
	virtual std::unique_ptr<Projection::Connector> get_section(
	    MultiIndexSequence const& sequence) const override;

	virtual std::unique_ptr<Projection::Connector> copy() const override;
	virtual std::unique_ptr<Projection::Connector> move() override;

protected:
	virtual std::ostream& print(std::ostream& os) const override;
	virtual bool is_equal_to(Projection::Connector const& other) const override;

private:
	dapr::PropertyHolder<MultiIndexSequence> m_input_sequence;
	dapr::PropertyHolder<MultiIndexSequence> m_output_sequence;
	dapr::PropertyHolder<MultiIndexSequence> m_connection_sequence;
};

} // namespace common
} // namespace grenade
