#pragma once
#include "grenade/common/genpybind.h"
#include "grenade/common/multi_index_sequence.h"
#include "grenade/common/projection.h"
#include "hate/visibility.h"

namespace grenade {
namespace common GENPYBIND_TAG_GRENADE_COMMON {

/**
 * Static connector base without parameterization.
 */
struct SYMBOL_VISIBLE GENPYBIND(visible) StaticConnector : public Projection::Connector
{
	virtual bool valid(
	    size_t input_port_on_connector,
	    Projection::Connector::Dynamics const& dynamics) const override;

	virtual bool valid(
	    size_t input_port_on_connector,
	    Projection::Connector::Parameterization const& parameterization) const override;

	/**
	 * Get sequence of synaptic connections generated by connector.
	 * This sequence describes the connectivity of the synapses between input and output
	 * sequences.
	 * @param sequence Sequence for which to get contained connections
	 */
	virtual std::unique_ptr<MultiIndexSequence> get_synapse_connections(
	    MultiIndexSequence const& sequence) const = 0;

	virtual size_t get_num_synapses(MultiIndexSequence const& sequence) const override;

	/**
	 * Static connectors have no input ports.
	 */
	virtual std::vector<Vertex::Port> get_input_ports() const override;

	/**
	 * Static connectors have no output ports.
	 */
	virtual std::vector<Vertex::Port> get_output_ports() const override;
};

} // namespace common
} // namespace grenade
