#include "grenade/common/genpybind.h"

GENPYBIND_TAG_GRENADE_COMMON
GENPYBIND_MANUAL({ parent.attr("__variant__") = "pybind11"; })

#include "grenade/common/compartment_on_cell.h"
#include "grenade/common/connection_on_executor.h"
#include "grenade/common/edge.h"
#include "grenade/common/edge_on_topology.h"
#include "grenade/common/execution_instance_id.h"
#include "grenade/common/input_data.h"
#include "grenade/common/inter_topology_hyper_edge.h"
#include "grenade/common/linked_topology.h"
#include "grenade/common/multi_index.h"
#include "grenade/common/multi_index_sequence.h"
#include "grenade/common/multi_index_sequence/cartesian_product.h"
#include "grenade/common/multi_index_sequence/cuboid.h"
#include "grenade/common/multi_index_sequence/list.h"
#include "grenade/common/multi_index_sequence_dimension_unit/cell_on_population.h"
#include "grenade/common/multi_index_sequence_dimension_unit/compartment_on_cell.h"
#include "grenade/common/output_data.h"
#include "grenade/common/partitioned_vertex.h"
#include "grenade/common/population.h"
#include "grenade/common/port_data.h"
#include "grenade/common/port_data/batched.h"
#include "grenade/common/resource_estimator.h"
#include "grenade/common/time_domain_on_topology.h"
#include "grenade/common/time_domain_runtimes.h"
#include "grenade/common/topology.h"
#include "grenade/common/topology_rewrite.h"
#include "grenade/common/vertex.h"
#include "grenade/common/vertex_on_topology.h"
#include "grenade/common/vertex_port_type.h"
