@Library("jenlib") _

Map<String, Object> pipelineOptions = [
		projects: ["grenade"],
		container: [app: "dls-core"],
		moduleOptions: [modules: ["ppu-toolchain"]],
		notificationChannel: "#dls-software",
		configureInstallOptions: "--build-profile=ci",
		testSlurmResource: getHxTestResource(3),
		preTestHook: { configureHxCubeBitfile() },
		testOptions: "--test-execall -j1"
]

withCcache() {
	wafDefaultPipeline(pipelineOptions)
}
