@Library("jenlib@ebrains-4.0") _

Map<String, Object> pipelineOptions = [
		projects: ["grenade"],
		setupOptions: "--release-branch=ebrains-4.0",
		container: [app: "dls-core"],
		moduleOptions: [modules: ["ppu-toolchain"]],
		notificationChannel: "#dls-software",
		configureInstallOptions: "--build-profile=ci",
		testSlurmResource: [partition: "cube", wafer: 62, "fpga-without-aout": 3],
		preTestHook: { configureHxCubeBitfile() },
		testOptions: "--test-execall -j1"
]

withCcache() {
	wafDefaultPipeline(pipelineOptions)
}
