#pragma once

#include "grenade/vx/genpybind.h"

GENPYBIND_TAG_GRENADE_VX_NETWORK_ABSTRACT
GENPYBIND_MANUAL({
	parent.attr("__variant__") = "pybind11";
	parent->py::module::import("pyhalco_hicann_dls_vx_v3");
	parent->py::module::import("pyhaldls_vx_v3");
	parent->py::module::import("pylola_vx_v3");
	parent->py::module::import("pyccalix");
	parent->py::module::import("pygrenade_common");
	parent->py::module::import("_pygrenade_vx_execution");
	parent->py::module::import("_pygrenade_vx_signal_flow");
	parent->py::module::import("_pygrenade_vx_network");
})

#include "grenade/vx/network/abstract/calibration.h"
#include "grenade/vx/network/abstract/calibration/fixture.h"
#include "grenade/vx/network/abstract/calibration/jit.h"
#include "grenade/vx/network/abstract/clock_cycle_time_domain_runtimes.h"
#include "grenade/vx/network/abstract/execution_instance_global.h"
#include "grenade/vx/network/abstract/executor_global.h"
#include "grenade/vx/network/abstract/mapper.h"
#include "grenade/vx/network/abstract/mapper/greedy.h"
#include "grenade/vx/network/abstract/mapping/cadc_recorder.h"
#include "grenade/vx/network/abstract/mapping/calibrated_neuron.h"
#include "grenade/vx/network/abstract/mapping/chip.h"
#include "grenade/vx/network/abstract/mapping/external_source_neuron.h"
#include "grenade/vx/network/abstract/mapping/locally_placed_neuron.h"
#include "grenade/vx/network/abstract/mapping/madc_recorder.h"
#include "grenade/vx/network/abstract/mapping/plasticity_rule.h"
#include "grenade/vx/network/abstract/mapping/poisson_source_neuron.h"
#include "grenade/vx/network/abstract/mapping/spike_recorder.h"
#include "grenade/vx/network/abstract/mapping/uncalibrated_neuron.h"
#include "grenade/vx/network/abstract/mapping/uncalibrated_synapse.h"
#include "grenade/vx/network/abstract/multi_index_sequence_dimension_unit/atomic_neuron_on_compartment.h"
#include "grenade/vx/network/abstract/multicompartment/compartment.h"
#include "grenade/vx/network/abstract/multicompartment/compartment_connection/conductance.h"
#include "grenade/vx/network/abstract/multicompartment/environment.h"
#include "grenade/vx/network/abstract/multicompartment/evolutionary/parameters.h"
#include "grenade/vx/network/abstract/multicompartment/mechanism/capacitance.h"
#include "grenade/vx/network/abstract/multicompartment/mechanism/synaptic_conductance.h"
#include "grenade/vx/network/abstract/multicompartment/mechanism/synaptic_current.h"
#include "grenade/vx/network/abstract/multicompartment/mechanism_on_compartment.h"
#include "grenade/vx/network/abstract/multicompartment/neuron.h"
#include "grenade/vx/network/abstract/multicompartment/neuron_circuit.h"
#include "grenade/vx/network/abstract/multicompartment/placement/algorithm.h"
#include "grenade/vx/network/abstract/multicompartment/placement/algorithm_brute_force.h"
#include "grenade/vx/network/abstract/multicompartment/placement/algorithm_dummy.h"
#include "grenade/vx/network/abstract/multicompartment/placement/algorithm_evolutionary.h"
#include "grenade/vx/network/abstract/multicompartment/placement/algorithm_result.h"
#include "grenade/vx/network/abstract/multicompartment/placement/algorithm_ruleset.h"
#include "grenade/vx/network/abstract/multicompartment/synaptic_input_environment.h"
#include "grenade/vx/network/abstract/multicompartment/synaptic_input_environment/conductance.h"
#include "grenade/vx/network/abstract/multicompartment/synaptic_input_environment/current.h"
#include "grenade/vx/network/abstract/multicompartment/top_bottom.h"
#include "grenade/vx/network/abstract/multicompartment/unplaced_neuron_circuit.h"
#include "grenade/vx/network/abstract/parameter_interval.h"
#include "grenade/vx/network/abstract/placement/greedy_placer.h"
#include "grenade/vx/network/abstract/placement/placer.h"
#include "grenade/vx/network/abstract/placement_result.h"
#include "grenade/vx/network/abstract/plasticity_rule.h"
#include "grenade/vx/network/abstract/plasticity_rule_generator.h"
#include "grenade/vx/network/abstract/population_cell/calibrated.h"
#include "grenade/vx/network/abstract/population_cell/delay.h"
#include "grenade/vx/network/abstract/population_cell/external_source.h"
#include "grenade/vx/network/abstract/population_cell/locally_placed.h"
#include "grenade/vx/network/abstract/population_cell/poisson_source.h"
#include "grenade/vx/network/abstract/population_cell/spikeio_source.h"
#include "grenade/vx/network/abstract/population_cell/uncalibrated.h"
#include "grenade/vx/network/abstract/projection_synapse/uncalibrated.h"
#include "grenade/vx/network/abstract/projection_synapse/uncalibrated_signed.h"
#include "grenade/vx/network/abstract/recorder.h"
#include "grenade/vx/network/abstract/recorder/cadc.h"
#include "grenade/vx/network/abstract/recorder/madc.h"
#include "grenade/vx/network/abstract/recorder/pad.h"
#include "grenade/vx/network/abstract/recorder/spike.h"
#include "grenade/vx/network/abstract/resource_estimator/population.h"
#include "grenade/vx/network/abstract/vertex_port_type/analog_observable.h"
#include "grenade/vx/network/abstract/vertex_port_type/cadc_samples.h"
#include "grenade/vx/network/abstract/vertex_port_type/madc_samples.h"
#include "grenade/vx/network/abstract/vertex_port_type/spike.h"
#include "grenade/vx/network/abstract/vertex_port_type/synapse_observable.h"
#include "grenade/vx/network/abstract/vertex_port_type/synaptic_input.h"
#include "grenade/vx/network/abstract/vertex_port_type/weight.h"
