#pragma once
#include <atomic>
#include <optional>
#include <set>
#include <vector>

#include "grenade/vx/config.h"
#include "grenade/vx/data_map.h"
#include "grenade/vx/execution_instance.h"
#include "grenade/vx/graph.h"
#include "grenade/vx/types.h"
#include "halco/hicann-dls/vx/chip.h"
#include "haldls/vx/synapse_driver.h"
#include "hate/history_wrapper.h"
#include "hate/visibility.h"
#include "lola/vx/cadc.h"
#include "lola/vx/synapse.h"
#include "stadls/vx/playback_generator.h"
#include "stadls/vx/playback_program_builder.h"

namespace grenade::vx {

/**
 * Builder for a single ExecutionInstance.
 * Vertices are processed resulting in a playback sequence and result structure.
 * Once executed, the result structure stores resulting measurements which can be processed to
 * be fed back into a graph executor.
 */
class ExecutionInstanceBuilder
{
public:
	/**
	 * Construct builder.
	 * @param graph Graph to use for locality and property lookup
	 * @param execution_instance Local execution instance to build for
	 * @param input_list Input list to use for input data lookup
	 * @param data_output Data output from depended-on executions to use for data lookup
	 * @param chip_config Chip configuration to use
	 */
	ExecutionInstanceBuilder(
	    Graph const& graph,
	    coordinate::ExecutionInstance const& execution_instance,
	    DataMap const& input_list,
	    DataMap const& data_output,
	    ChipConfig const& chip_config) SYMBOL_VISIBLE;

	/**
	 * Preprocess by single visit of all local vertices.
	 */
	void pre_process() SYMBOL_VISIBLE;

	/**
	 * Register epilogue playback sequence, which is appended to the sequence generated by the
	 * graph processing.
	 * @param builder PlaybackProgramBuilder moved after the generated sequence
	 */
	void register_epilogue(stadls::vx::PlaybackProgramBuilder&& builder) SYMBOL_VISIBLE;

	/**
	 * Register prologue playback sequence, which is prepended to the sequence generated by the
	 * graph processing.
	 * @param builder PlaybackProgramBuilder moved before the generated sequence
	 */
	void register_prologue(stadls::vx::PlaybackProgramBuilder&& builder) SYMBOL_VISIBLE;

	/**
	 * Generate playback sequence.
	 * @return PlaybackProgram generated via local graph traversal
	 */
	stadls::vx::PlaybackProgram generate() SYMBOL_VISIBLE;

	/**
	 * Postprocess by visit of all local vertices to be post processed after execution.
	 * This resets the internal state of the builder to be ready for the next time step.
	 * @return DataMap of locally computed results
	 */
	DataMap post_process() SYMBOL_VISIBLE;
	void post_process(Graph::vertex_descriptor const vertex) SYMBOL_VISIBLE;

	/**
	 * Switch to enable HAGEN-mode workarounds needed for HXv1.
	 * TODO: remove once HXv2 is working.
	 */
	bool enable_hagen_workarounds = true;

private:
	Graph const& m_graph;
	coordinate::ExecutionInstance m_execution_instance;
	DataMap const& m_input_list;
	DataMap const& m_data_output;

	DataMap m_local_external_data;

	hate::HistoryWrapper<ChipConfig> m_config;

	stadls::vx::PlaybackProgramBuilder m_builder_epilogue;
	stadls::vx::PlaybackProgramBuilder m_builder_prologue;

	stadls::vx::PlaybackProgramBuilder m_builder_input;

	stadls::vx::PlaybackProgramBuilder m_builder_neuron_reset;

	std::vector<Graph::vertex_descriptor> m_post_vertices;

	stadls::vx::PlaybackProgram m_program;

	std::optional<Graph::vertex_descriptor> m_event_output_vertex;

	bool m_postprocessing;

	DataMap m_local_data;
	DataMap m_local_data_output;

	typedef halco::common::typed_array<bool, halco::hicann_dls::vx::HemisphereOnDLS>
	    ticket_request_type;
	ticket_request_type m_ticket_requests;
	typedef std::optional<stadls::vx::PlaybackProgram::ContainerTicket<lola::vx::CADCSamples>>
	    ticket_type;
	ticket_type m_ticket;
	ticket_type m_ticket_baseline;
	stadls::vx::PlaybackProgramBuilder m_builder_cadc_readout;
	stadls::vx::PlaybackProgramBuilder m_builder_cadc_readout_baseline;

	halco::common::typed_array<bool, halco::hicann_dls::vx::NeuronResetOnDLS> m_neuron_resets;
	halco::common::typed_array<bool, halco::hicann_dls::vx::PADIBusOnDLS> m_used_padi_busses;

	/**
	 * Check if any incoming vertex requires post processing.
	 * @param descriptor Vertex descriptor to check for
	 * @return Boolean value
	 */
	bool inputs_available(Graph::vertex_descriptor const descriptor) const SYMBOL_VISIBLE;

	/**
	 * Process single vertex.
	 * This function is called in both preprocess and postprocess depending on whether the vertex
	 * requires post-execution processing.
	 * @param vertex Vertex descriptor
	 * @param data Data associated with vertex
	 */
	template <typename Vertex>
	void process(Graph::vertex_descriptor const vertex, Vertex const& data);

	/**
	 * Get whether input list is complete for the local execution instance.
	 * @return Boolean value
	 */
	bool has_complete_input_list() const;
};

} // namespace grenade::vx
